### ISSUE TITLE
Tag first release.

### ISSUE THREAD

**Issue by 9600** [myriadrf/LimeSuiteNG#95]
Tag the first Lime Suite NG release once:

- [x] Apps can simultaneously link against Lime Suite and Lime Suite NG (#92)
- [x] gr-limesdr blocks renamed (#93)
- [ ] Tested with selected applications and hardware (#94).
- [ ] Packaging files in place
- [ ] New packaging build infrastructure, e.g. OBS.
